"use client";

import { useEffect, useState } from "react";

type Draft = { text: string; company: string; role: string; location: string; language: string; source_url: string; retrieved: string };
const emptyDraft: Draft = { text: "", company: "", role: "", location: "", language: "", source_url: "", retrieved: "" };

export default function CreateCvPage() {
  const [draft, setDraft] = useState<Draft>(emptyDraft);
  const [message, setMessage] = useState("");
  const [threadId, setThreadId] = useState<string | null>(null);
  const [evidence, setEvidence] = useState<{ requirement_id: string; source_path: string; excerpt: string; confidence: number }[]>([]);
  const [summary, setSummary] = useState("");
  const [applicationPath, setApplicationPath] = useState("");
  const [busy, setBusy] = useState(false);
  const [step, setStep] = useState(1);
  useEffect(() => { try { const saved = sessionStorage.getItem("job-draft"); if (saved) setDraft({ ...emptyDraft, ...JSON.parse(saved) }); } catch { /* Ignore malformed browser-only draft state. */ } }, []);
  const update = (key: keyof Draft, value: string) => setDraft((current) => { const next = { ...current, [key]: value }; sessionStorage.setItem("job-draft", JSON.stringify(next)); return next; });
  const fetchUrl = async () => { const response = await fetch("/api/job-url", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url: draft.source_url }) }); const result = await response.json(); if (!response.ok) { setMessage(result.detail || "Could not fetch this URL."); return; } setDraft((current) => { const next = { ...current, text: result.text, retrieved: result.retrieved }; sessionStorage.setItem("job-draft", JSON.stringify(next)); return next; }); setMessage("Job text fetched. Review it before continuing."); };
  const startWorkflow = async () => { if (busy) return; setBusy(true); try { const response = await fetch("/api/workflow/start", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: draft.text, metadata: { company: draft.company, role: draft.role, location: draft.location, language: draft.language, source_url: draft.source_url, retrieved: draft.retrieved } }) }); const result = await response.json(); if (!response.ok) { setMessage(result.detail || "Could not start workflow."); return; } setThreadId(result.thread_id); setEvidence(result.evidence?.candidates || []); setStep(2); setMessage(result.evidence?.candidates?.length ? "Evidence is ready for review." : "No matching evidence found. Add clearer skills or experience to the job post, then start again."); } finally { setBusy(false); } };
  const resumeWorkflow = async (action: "approve" | "reject") => { if (!threadId) return; const response = await fetch(`/api/workflow/${threadId}/resume`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision: { action, evidence_ids: [], notes: "" } }) }); const result = await response.json(); if (!response.ok) { setMessage(result.detail || "Could not save the review."); return; } setSummary(result.drafts?.cv?.summary || ""); setStep(action === "approve" ? 3 : 1); setMessage(action === "approve" ? "Evidence approved. Your draft is ready." : "Evidence rejected. Review the job again."); };
  const finalizeWorkflow = async () => { if (!threadId || busy) return; setBusy(true); try { const response = await fetch(`/api/workflow/${threadId}/finalize`, { method: "POST" }); const result = await response.json(); if (!response.ok) { setMessage(result.detail || "Could not finalize the application."); return; } setApplicationPath(result.path); setStep(4); setMessage("Application finalized."); } finally { setBusy(false); } };
  const steps = ["Job post", "Evidence", "Draft", "Review"];
  return <section className="form-page"><h1>Start an application</h1><p className="lede">Paste a job post, review the matching evidence, then generate your targeted application.</p><div className="workflow-progress"><div><strong>Step {step} of {steps.length}</strong><span>{steps[step - 1]}</span></div><progress max={steps.length} value={step}>{step} of {steps.length}</progress><ol aria-label="Application progress">{steps.map((label, index) => <li className={index + 1 < step ? "complete" : undefined} aria-current={step === index + 1 ? "step" : undefined} key={label}>{label}</li>)}</ol></div>
    <form className="create-record-form" aria-busy={busy} onSubmit={(event) => { event.preventDefault(); setMessage(draft.text.trim() ? "Draft saved in this browser session." : "Paste the job description first."); }}>
      <label>Job post text<textarea rows={10} value={draft.text} onChange={(event) => update("text", event.target.value)} required /></label>
      <label>Public job URL<input type="url" value={draft.source_url} onChange={(event) => update("source_url", event.target.value)} placeholder="https://…" /></label>
      <button className="button button-secondary" type="button" onClick={() => void fetchUrl()} disabled={!draft.source_url}>Fetch URL</button>
      <div className="editor-field-grid"><label>Company<input value={draft.company} onChange={(event) => update("company", event.target.value)} required /></label><label>Role<input value={draft.role} onChange={(event) => update("role", event.target.value)} required /></label><label>Location<input value={draft.location} onChange={(event) => update("location", event.target.value)} /></label><label>Language<input value={draft.language} onChange={(event) => update("language", event.target.value)} /></label></div>
      <button className="button button-primary" type="button" onClick={() => void startWorkflow()} disabled={busy || !draft.text.trim() || !draft.company || !draft.role}>{busy ? "Building…" : "Build application"}</button>{busy && <p role="status" aria-live="polite">Building application… checking the job post against your profile.</p>}{step === 2 && <div className="review-card"><h2>Review evidence</h2>{evidence.length ? <><ul>{evidence.map((item, index) => <li key={`${item.source_path}-${index}`}><strong>{item.requirement_id}</strong> · {item.excerpt}<small>Source: {item.source_path} · Confidence: {Math.round(item.confidence * 100)}%</small></li>)}</ul><button className="button button-primary" type="button" onClick={() => void resumeWorkflow("approve")}>Approve evidence</button></> : <p>No matching profile evidence was found. This workflow is paused; it will not retry automatically. Update the job details or your profile, then start again.</p>}<button className="button button-secondary" type="button" onClick={() => void resumeWorkflow("reject")}>Reject and revise</button></div>}{step === 3 && <div className="review-card"><h2>Draft ready</h2><p role="status">{summary || "Your evidence-bound draft is ready for final review."}</p><button className="button button-primary" type="button" onClick={() => void finalizeWorkflow()} disabled={busy}>{busy ? "Finalizing…" : "Finalize application"}</button></div>}{step === 4 && <div className="review-card"><h2>Application complete</h2><p role="status">Saved to {applicationPath}.</p><a className="button button-secondary" href={`/applications/${applicationPath.split("/").pop()}`}>Open application</a></div>}{message && <p role="status">{message}</p>}
    </form>
  </section>;
}
